### ISSUE TITLE
"String was not recognized as a valid Boolean"

### ISSUE THREAD

**Issue by PcChip** [christaylorcodes/ConnectWiseManageAPI#1]
Hi,

When I run this:  
`$companies = Get-CWMCompany -all`

it starts downloading all the companies, however at the end it errors out with:  
  

> Invoke-CWMWebRequest : An exception has been thrown.
> --> The remote server returned an error: (500) Internal Server Error.
> An error has been thrown.
> --> 
> --> {
>   "code": "ConnectWiseApi",
>   "message": "String was not recognized as a valid Boolean."
> }
> at Invoke-CWMWebRequest, C:\Program Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.3.3.0\Private\Invoke\Invoke-CWMWebRequest.ps1: line 41
> at Invoke-CWMAllResult, C:\Program Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.3.3.0\Private\Invoke\Invoke-CWMAllResult.ps1: line 29
> at Invoke-CWMGetMaster, C:\Program Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.3.3.0\Private\Invoke\Invoke-CWMGetMaster.ps1: line 44
> at Get-CWMCompany, C:\Program Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.3.3.0\Public\Company\Companies\Get-CWMCompany.ps1: line 17
> at <ScriptBlock>, <No file>: line 21
> At C:\Program Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.3.3.0\Private\Invoke\Invoke-CWMAllResult.ps1:29 char:23
> +         $PageResult = Invoke-CWMWebRequest -Arguments $Arguments
> +                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>     + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-CWMWebRequest

Is there anything I can do to loop through all the companies? I'm just looking for custom fields

**Comment by christaylorcodes** [comment]
Sorry but this error has nothing to do with the module. As the error message states, this is an internal server error caused by a boolean field being populated with a string in one or more of your companies. Besides updating the erroneous entry you can try to restrict what fields are returned with the `-fields` parameter and see if that will bypass the error.
`Get-CWMCompany -fields @('id','name') -all`
