### ISSUE TITLE
Get-CWMBoardTypeSubTypeItemAssociation ?

### ISSUE THREAD

**Issue by Viajaz** [christaylorcodes/ConnectWiseManageAPI#20]
We want to obtain [associated Items](https://developer.connectwise.com/Products/Manage/REST#/BoardTypeSubTypeItemAssociation) for a given Board Type and Board Type Subtype so we can programmatically create tickets with a populated Item field.

This would be handy to have as a Cmdlet.

An example workaround is to call the private Cmdlet `Invoke-CWMGetMaster`:
```powershell
$CWMAPIModule = Import-Module -Name 'ConnectWiseManageAPI' -Cmdlet 'Invoke-CWMGetMaster' -PassThru
& $CWMAPIModule { Invoke-CWMGetMaster -Arguments @{Condition="subType/id = 1234"} -Endpoint '/service/boards/4321/typeSubTypeItemAssociations' }
```

**Comment by christaylorcodes** [comment]
Issue resolved in version: 0.4.4.1
e459530
