### ISSUE TITLE
Get-CWMDocument Missing recordId and recordType Parameters

### ISSUE THREAD

**Issue by Viajaz** [christaylorcodes/ConnectWiseManageAPI#21]
`Get-CWMDocument` is missing `recordId` and `recordType` Cmdlet parameters as per [Documents](https://developer.connectwise.com/Products/Manage/REST#/Documents/getSystemDocuments) and [Help markdown](https://github.com/christaylorcodes/ConnectWiseManageAPI/blob/master/Docs/Get-CWMDocument.md).

https://github.com/christaylorcodes/ConnectWiseManageAPI/blob/75ad0b72ee369a5de49f07d290c34293173f6e8c/ConnectWiseManageAPI/Public/System/Documents/Get-CWMDocument.ps1

Example workaround
```powershell
$CWMAPIModule = Import-Module -Name 'ConnectWiseManageAPI' -Cmdlet @('Invoke-CWMWebRequest', 'New-CWMUrl')  -PassThru
& $CWMAPIModule {
    $Result = Invoke-CWMWebRequest -Arguments @{
        Uri = (New-CWMUrl -Endpoint "/system/documents" -URLParameters "&recordType=Ticket&recordId=1234")
        Method = 'GET'
    }
    if($Result.content){
        try{ $Result = $Result.content | ConvertFrom-Json }
        catch{
            Write-Error "There was an issue converting the results from JSON."
            $_
        }
    }
    $Result
}
```

**Comment by christaylorcodes** [comment]
Issue resolved in version: 0.4.4.1
e459530
