### ISSUE TITLE
Error in Get-CWMCompanyTypeAssociation

### ISSUE THREAD

**Issue by scubes13** [christaylorcodes/ConnectWiseManageAPI#25]
Line 20 reads as:
`    $Endpoint = "/company/companies/$(parentId)/typeAssociations"`

This was breaking. I updated in my local copy as:
``    $Endpoint = "/company/companies/$($parentId)/typeAssociations"``

It worked after this change was made.

**Comment by christaylorcodes** [comment]
6fe056c
Updated
