### ISSUE TITLE
Doc Update: New-CWMCompanyTypeAssociation

### ISSUE THREAD

**Issue by scubes13** [christaylorcodes/ConnectWiseManageAPI#28]
The example reads:
`New-CWMCompanyTypeAssociation -company @{id = 4385} -Type @{type = @{id = 68}}`

In testing, it should read as:
`New-CWMCompanyTypeAssociation -company @{id = 4385} -Type @{id = 68}`

**Comment by christaylorcodes** [comment]
Docs updated
