### ISSUE TITLE
create new members via Powershell

### ISSUE THREAD

**Issue by paynent** [christaylorcodes/ConnectWiseManageAPI#3]
I'm guessing this isn't a capability at this point, but is there anyway to create a new member through the API/Powershell? I'd like to implement this as part of a new user script.

**Comment by christaylorcodes** [comment]
Functionality added with da7c901
[New-CWMMember](https://github.com/christaylorcodes/ConnectWiseManageAPI/blob/master/Docs/New-CWMMember.md)
