### ISSUE TITLE
Unable to add configuration item to a ticket.

### ISSUE THREAD

**Issue by AHelsby** [christaylorcodes/ConnectWiseManageAPI#30]
Attempting to add a new configuration item to a ticket gives me the following error

`New-CWMTicketConfiguration -ticketId 1599150 -deviceIdentifier 18217

Invoke-CWMWebRequest : An exception has been thrown.
--> The remote server returned an error: (400) Bad Request.
An error has been thrown.
-->
--> {
  "code": "InvalidObject",
  "message": "configuration object is invalid",
  "errors": [
    {
      "code": "MissingRequiredField",
      "message": "id or deviceIdentifier is required.",
      "resource": "configuration",
      "field": "id"
    }
  ]
}
at Invoke-CWMWebRequest, C:\Program
Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.4.8.0\Private\Invoke\Invoke-CWMWebRequest.ps1: line 42
at Invoke-CWMNewMaster, C:\Program
Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.4.8.0\Private\Invoke\Invoke-CWMNewMaster.ps1: line 38
at New-CWMTicketConfiguration, C:\Program Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.4.8.0\Public\Service\TicketConfigurations\New-CWMTicketConfiguration.ps1: line 12
at <ScriptBlock>, <No file>: line 1
At C:\Program Files\WindowsPowerShell\Modules\ConnectWiseManageAPI\0.4.8.0\Private\Invoke\Invoke-CWMNewMaster.ps1:38
char:19
 ...        $Result = Invoke-CWMWebRequest -Arguments $WebRequestArguments
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
     FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Invoke-CWMWebRequest`


I've confirmed that id 18217 is a valid id for that company, I've tried adding the configuration name in and that fails with  Configuration configurationname not found.
Get-cwmticketconfiguration -ticketid 1599150 returns the other configuration items that were manually added in the gui and all the id's match

Any clues as to why it thinks deviceidentifier is required when it's included?

**Comment by christaylorcodes** [comment]
Thank you for submitting the issue.
`id or deviceIdentifier is required.`
Though the error states it is looking for the `id` OR `deviceIdentifier` it appears to only be looking for `id`.
I have updated the function to accept either and pass only the `id`.
Please update to 0.4.9.0 and try again.
