### ISSUE TITLE
How to assign a resource to a ticket?

### ISSUE THREAD

**Issue by chaoscreater** [christaylorcodes/ConnectWiseManageAPI#33]
Hi,

I'm trying to figure out how to assign a resource and even though I get a HTTP 200 response using the following code below, no resources get assigned:

```
	$closeBody = "[{  
				op : 'add',
				path :'resources',
				value: 'xxxxxxxxx'
				}]"
					
	
				
		
				
    #Update ticket status with PATCH to OPEN first, (in case we closed it, which prevents us from adding time entries)
    try {
        $res = Invoke-RestMethod -Method Patch  -URI "$CWURL/v4_6_release/apis/3.0/service/tickets/$($ticket.objectId)" -headers $Headers -Body $closeBody -ContentType "application/json" 
    }
    catch {
        Write-Warning "Catch clause"
        Start-Sleep -Seconds 5
        $res = Invoke-RestMethod -Method Patch  -URI "$CWURL/v4_6_release/apis/3.0/service/tickets/$($ticket.objectId)" -headers $Headers -Body $closeBody -ContentType "application/json" 
    }
	
```

**Comment by christaylorcodes** [comment]
`New-CWMScheduleEntry -member @{identifier = 'ctaylor'} -objectId $TicketId -type @{id = $TypeId} `
[Docs](https://github.com/christaylorcodes/ConnectWiseManageAPI/blob/master/Docs/New-CWMScheduleEntry.md)

**Comment by chaoscreater** [comment]
@christaylorcodes - where can we get the $TypeID from?

I'm not using your script because I already have my own script and I just need to make a small addition to it. Wondering if you could provide some assistance please? 

I can remove a resource from the schedule like this:

```
$ID = "12345"
Invoke-RestMethod -Method DELETE -URI "$CWURL/v4_6_release/apis/3.0/schedule/entries/$ID" -headers $Headers -ContentType "application/json" 
```

I'm just trying to figure out how to add someone as a resource to the schedule. I just need to figure out the URI bit in the middle.....
