### ISSUE TITLE
Any example of updating a ticket?

### ISSUE THREAD

**Issue by Absoblogginlutely** [christaylorcodes/ConnectWiseManageAPI#4]
Was wondering if someone had a working example to udpate a ticket. I'm not sure if the whole ticket needs to retrieved, the values change and then the whole thing replaced.

I'm currently struggling with what to put in the path/value statement.

I currently have
>$a=get-cwmticket
>$a.source.name
CHANGE ME

 $updateparam=@{
 ticketid = 1229737
 Operation = 'replace'
 Path = 'Source'
 Value ='Phone'}
 }
update-cwmticket @updateparam

But this generates the path source is not valid. I've tried changing path to source.name, Source/Name etc but obviously not getting it quite right.

**Comment by gooseleggs** [comment]
Hello - I dont have an example, but what I do when I get an error that I seem to get no meaningful answer for it is to edit the appropriate Invoke-xxxx file to show me the body of the request (change write-verbose to Write-host.  Then I take that - throw it into postman and see what error CW is actually spitting back.  I need to modify it specifically, as using an Azure function is that is painful to debug (I must be doing something wrong).  Anyway, this may be of some use or not.

**Comment by Absoblogginlutely** [comment]
For reference for anyone else with this issue, the following works for nonproject tickets. I'm changing the source here from the default of CHANGE ME to our company name (value 10). I still need to work on Project tickets as the get-cwmprojectticket returns all the project tickets and doesn't have an option for ticketid.
```
$tid=1368680
$t=get-cwmticket -id $tid
$t.source.name
if ($t.source.name -eq 'CHANGEME') {
$updateparm=@{
ticketid = $tid
Operation = 'replace'
Path = 'source/id'
Value ='10'}


update-cwmticket @updateparm
```
