### ISSUE TITLE
Get-CWMCompanyContact does not return any Company identifiers

### ISSUE THREAD

**Issue by JD405** [christaylorcodes/ConnectWiseManageAPI#40]
The Get-CWMCompanyContact function does not return any Company identifiers in order to link the contact back to the company they are assigned to. The Company and Site values come back blank for every record I search, using "Get-CWMCompanyContact -Condition 'defaultPhoneNbr like "%########%"' -all". I was hoping to build a lookup for our phone system to pull the contact and company information for a customer when they call in.

**Comment by christaylorcodes** [comment]
I am not sure why they would come back as blank for you. Check the permissions of the account you are using.
`Get-CWMMySecurity`
