### ISSUE TITLE
New Ticket: Severity and Impact are defined as Int when should be string

### ISSUE THREAD

**Issue by gooseleggs** [christaylorcodes/ConnectWiseManageAPI#6]
When trying to use the New-CWMTicket both the priority and severity are defined as `Int32`.  However, these are defined as strings in the Connectwise API Documentation

```
"severity": "Low",
  "impact": "Low",
```
This is a bug, and should be changed

**Comment by christaylorcodes** [comment]
Thanks for raising an issue.
ce923fc
