### ISSUE TITLE
Add Warehouse and Inventory functions

### ISSUE THREAD

**Issue by damiankw** [christaylorcodes/ConnectWiseManageAPI#60]
It would be good to have access to the Inventory, Stock on Hand, which requires access to Warehouses and Warehouse bins.

Examples:

`Get-Warehouse`
_Will list all of your warehouses, standard -options apply._

`Get-WarehouseBin`
_Will list all of your warehouse bins, standard -options apply._

`Get-Inventory -parentId [WarehouseBinId]`
_Will list all of your inventory in the Warehouse Bin as required by the API, standard -options apply._

**Comment by christaylorcodes** [comment]
Merged pull request
