### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by AaronFalzon** [christaylorcodes/ConnectWiseManageAPI#8]
I think this is a small typo - 
Company/CompantStatuses
should be: Company/CompanyStatuses

Aaron.

**Comment by christaylorcodes** [comment]
I don't see this referenced anywhere can you be more descriptive with where you are seeing this, a link maybe.

**Comment by AaronFalzon** [comment]
Hey Chris,

[https://github.com/christaylorcodes/ConnectWiseManageAPI/tree/master/ConnectWiseManageAPI/Public/Company/CompantStatuses](https://github.com/christaylorcodes/ConnectWiseManageAPI/tree/master/ConnectWiseManageAPI/Public/Company/CompantStatuses)

**Comment by christaylorcodes** [comment]
Thank you for the info
4ac6487
